apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-dev
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  source:
    repoURL: https://github.com/sohampa/multicluster_deployment_argocd.git
    path: manifest/dev/
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
