apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-qa
  namespace: argocd
spec:
  destination:
    server: https://6D7212600DFAF34635A5F95BCBBB28C5.gr7.us-east-1.eks.amazonaws.com
    namespace: qa
  source:
    repoURL: https://github.com/sohampa/multicluster_deployment_argocd.git
    path: manifest/qa/
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
